local inserted = false
function DBMCPHeroesAll()
	if inserted then return end
	--여성 Best
	tinsert(DBM.Counts, {text= "[여]추천: BigWig",value = "BigWig",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\BigWig\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 가시여왕",value = "LadyofThorns",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\LadyofThorns\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 넥서스헌터",value = "NexusHunter",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\NexusHunter\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 볼스카야",value = "Volskaya",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Volskaya\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 아테나",value = "Athena",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Athena\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 정원사",value = "Gardens",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Gardens\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]디아블로: 악마사냥꾼",value = "DemonHunter",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\DemonHunter\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]디아블로: 야만용사",value = "Barbarian",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Barbarian\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]디아블로: 성전사",value = "Crusader",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Crusader\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]오버워치: 메이",value = "Mei",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Mei\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]와우: 제이나",value = "Jaina",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Jaina\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]와우: 화이트메인",value = "Whitemane",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Whitemane\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]와우: 이렐",value = "Yrel",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Yrel\\",max = 5})

	--남성 Best
	tinsert(DBM.Counts, {text= "[남]히오스: 까마귀군주",value = "RavenLord",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\RavenLord\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 부두술사",value = "WitchDoctor",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\WitchDoctor\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 천사",value = "Angel",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Angel\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 티리엘",value = "Tyrael",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Tyrael\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 드렉타르",value = "DrekThar",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\DrekThar\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 아서스",value = "Arthas",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Arthas\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 안두인",value = "Anduin",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Anduin\\",max = 5})

	--추가분
	tinsert(DBM.Counts, {text= "[여]히오스: 거미여왕",value = "SpiderQueen",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\SpiderQueen\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 뱀신",value = "SnakeGod",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\SnakeGod\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 빛나래",value = "Brightwing",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Brightwing\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 오르피아",value = "Orphea",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Orphea\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]히오스: 장난감",value = "Toy18",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Toy18\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]오버워치: 디바 ",value = "DVa",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\DVa\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]와우: 리리",value = "LiLi",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\LiLi\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]와우: 마이에브",value = "Maiev",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Maiev\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]스타: 미라",value = "Mira",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Mira\\",max = 5})
	tinsert(DBM.Counts, {text= "[여]스타: 시즈탱크",value = "SiegeTank",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\SiegeTank\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 강령술사",value = "Necromancer",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Necromancer\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 데커드케인",value = "Deckard",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Deckard\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 메피스토",value = "Mephisto",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Mephisto\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 악마",value = "Demon",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Demon\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 메카티리엘",value = "TyraelMecha",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\TyraelMecha\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]디아블로: 임페리우스",value = "Imperius",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Imperius\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 가로쉬",value = "Garrosh",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Garrosh\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 가즈로",value = "Gazlowe",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Gazlowe\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 누더기",value = "Stitches",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Stitches\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 데스윙",value = "Deathwing",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Deathwing\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 일리단",value = "Illidan",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Illidan\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 레가르",value = "Rehgar",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Rehgar\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 말퓨리온",value = "Malfurion",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Malfurion\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 무라딘",value = "Muradin",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Muradin\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 반다르",value = "Vanndar",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Vanndar\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 폴스타트",value = "Falstad",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Falstad\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 엘리트타우렌족장들",value = "ETC",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\ETC\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 말가니스",value = "MalGanis",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\MalGanis\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]와우: 켈투자드",value = "Kelthuzad",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Kelthuzad\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]스타: 제라툴",value = "Zeratul",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Zeratul\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]스타: 타이커스",value = "Tychus",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Tychus\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]스타: 태사다르",value = "Tassadar",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Tassadar\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]히오스: 기본 ",value = "HoSdefault",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\HoSdefault\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]오버워치: 정크랫",value = "Junkrat",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Junkrat\\",max = 5})
	tinsert(DBM.Counts, {text= "[남]오버워치: 한조",value = "Hanzo",path = "Interface\\AddOns\\DBM-CountPack-HoTS\\Hanzo\\",max = 5})

	inserted = true	
end
